"""empty message

Revision ID: 04227dd80531
Revises: 70d9f6b385a7
Create Date: 2017-02-23 12:06:10.296853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04227dd80531'
down_revision = '70d9f6b385a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    # ### end Alembic commands ###
