"""empty message

Revision ID: 54e1c085f90b
Revises: 6a337a9b1c8e
Create Date: 2017-02-24 00:23:49.851424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54e1c085f90b'
down_revision = '6a337a9b1c8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'timestamp')
    # ### end Alembic commands ###
