"""empty message

Revision ID: 6a337a9b1c8e
Revises: 691cf7a01c25
Create Date: 2017-02-23 18:50:07.433122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a337a9b1c8e'
down_revision = '691cf7a01c25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('post_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'images', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_column('images', 'post_id')
    # ### end Alembic commands ###
