"""empty message

Revision ID: c978f03a934e
Revises: 54e1c085f90b
Create Date: 2017-02-25 17:35:11.240708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c978f03a934e'
down_revision = '54e1c085f90b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('contactEmail', sa.Text(), nullable=True))
    op.drop_column('posts', 'street')
    op.drop_column('posts', 'city')
    op.drop_column('posts', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('city', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('street', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('posts', 'contactEmail')
    op.drop_column('posts', 'address')
    # ### end Alembic commands ###
